fix partition order

diff --git a/bash/formatscript b/bash/formatscript
--- a/bash/formatscript
+++ b/bash/formatscript
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
-ENV_FILE="/tmp/partition.env"
-if [ ! -f "$ENV_FILE" ]; then
-    echo "Missing $ENV_FILE. Run partitionscript first."
-    exit 1
+BASE_DIR="/usr/local/share"
+VARS_FILE="$BASE_DIR/disk.sh"
+
+if [[ ! -f "$VARS_FILE" ]]; then
+  echo "Missing vars file: $VARS_FILE" >&2
+  exit 1
 fi
-source "$ENV_FILE"
+source "$VARS_FILE"
 
 echo "Defining partition paths..."
 
@@ -17,11 +19,12 @@ else
 fi
 
 BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
-ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
 
 if [ "$swapyn" == "y" ]; then
-    SWAP_PART="${DISK}${PART_SEP}3" || { echo "Failed to define swap partition"; exit 1; } 
-    echo "Success."
+    SWAP_PART="${DISK}${PART_SEP}2" || { echo "Failed to define swap partition"; exit 1; } 
+    ROOT_PART="${DISK}${PART_SEP}3" || { echo "Failed to define root partition"; exit 1; } 
+else 
+    ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
 fi
 
 # Format partitions
@@ -34,3 +37,5 @@ echo "Formating partitions..."
 mkfs.fat -F 32 "$BOOT_PART"  || { echo "Failed to format boot partition"; exit 1; } 
 mkfs.ext4 -F "$ROOT_PART"  || { echo "Failed to format root partition"; exit 1; } 
 echo "Success."
+
+bash /usr/local/share/bash/mountingscript.sh || { echo "install_base failed"; exit 1; }
diff --git a/bash/mountingscript b/bash/mountingscript
--- a/bash/mountingscript
+++ b/bash/mountingscript
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
-ENV_FILE="/tmp/partition.env"
-if [ ! -f "$ENV_FILE" ]; then
-    echo "Missing $ENV_FILE. Run partitionscript first."
-    exit 1
+BASE_DIR="/usr/local/share"
+VARS_FILE="$BASE_DIR/disk.sh"
+
+if [[ ! -f "$VARS_FILE" ]]; then
+  echo "Missing vars file: $VARS_FILE" >&2
+  exit 1
 fi
-source "$ENV_FILE"
+source "$VARS_FILE"
 
 
 echo "Defining partition paths..."
@@ -18,11 +20,13 @@ else
 fi
 
 BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
-ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
 
 if [ "$swapyn" == "y" ]; then
-    SWAP_PART="${DISK}${PART_SEP}3" || { echo "Failed to define swap partition"; exit 1; } 
+    ROOT_PART="${DISK}${PART_SEP}3" || { echo "Failed to define root partition"; exit 1; } 
+    SWAP_PART="${DISK}${PART_SEP}2" || { echo "Failed to define swap partition"; exit 1; } 
     echo "Success."
+else 
+    ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
 fi
 
 # Mount Root
@@ -30,7 +34,7 @@ echo "Mounting root..."
 mount "$ROOT_PART" /mnt
 echo "Success."
 
-# Mount Boot (Create the directory first)
+# Mount Boot 
 echo "Mounting boot..."
 mkdir -p /mnt/boot
 mount "$BOOT_PART" /mnt/boot
diff --git a/bash/partitionscript b/bash/partitionscript
--- a/bash/partitionscript
+++ b/bash/partitionscript
@@ -25,28 +25,23 @@ echo "Success."
 rootstart=1025
 
 
+if [ "$swapyn" = "y" ]; then
+    echo "Creating Swap Partition ($swapsize)..."
+    swapstart="${rootstart}MiB"
+    swapend="$((rootstart + swapsize))MiB"
+    parted -s "$TARGET_DISK" mkpart primary linux-swap "$swapstart" "$swapend" || { echo "Failed to create swap partition."; exit 1; }
+    echo "Success."
+
+    rootstart=$((rootstart + swapsize))
+fi
+
 echo "Creating root partition ($rootsize)..."
 rootend=$((rootstart + rootsize))
-parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB"
+parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB" || { echo "Failed to create root partition."; exit 1; }
 echo "Success."
-
-
-if [ "$swapyn" == "y" ]; then
-    echo "Creating Swap Partition ($swapsize)..."
-    parted -s "$TARGET_DISK" mkpart primary linux-swap "${rootend}MiB" "$((rootend + swapsize))MiB"
-    echo "Success."
-fi
 
 echo "Successfully created UEFI, root and swap partition."
 
-export swapyn
-export swapsize
-export rootsize
+bash /usr/local/share/bash/formatscript.sh || { echo "install_base failed"; exit 1; }
 
-ENV_FILE="/tmp/partition.env"
-cat > "$ENV_FILE" <<EOF
-export DISK="$TARGET_DISK"
-export rootsize="$rootsize"
-export swapsize="$swapsize"
-export swapyn="$swapyn"
-EOF
+
