feat: Implement UEFI/Legacy BIOS detection and bootloader installation, refactor partitioning and mounting scripts, and refresh the UI style.

diff --git a/bash/formatscript b/bash/formatscript
--- a/bash/formatscript
+++ b/bash/formatscript
@@ -21,26 +21,39 @@ else
     PART_SEP=""
 fi
 
-BOOT_PART="${DISK}${PART_SEP}1"
 
-if [[ "$swapyn" == "y" ]]; then
-    SWAP_PART="${DISK}${PART_SEP}2"
-    ROOT_PART="${DISK}${PART_SEP}3"
+if [ "$uefiyn" == "y" ]; then
+    BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
+
+    if [[ "$swapyn" == "y" ]]; then
+        SWAP_PART="${DISK}${PART_SEP}2" || { echo "Failed to define swap partition"; exit 1; } 
+        ROOT_PART="${DISK}${PART_SEP}3" || { echo "Failed to define root partition"; exit 1; } 
+    else
+        ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
+    fi
 else
-    ROOT_PART="${DISK}${PART_SEP}2"
+    if [[ "$swapyn" == "y" ]]; then
+        SWAP_PART="${DISK}${PART_SEP}1" || { echo "Failed to define swap partition"; exit 1; } 
+        ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define boot partition"; exit 1; } 
+    else
+        ROOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
+    fi
 fi
 
+echo "Formating partitions..."
 
 # Format partitions
+if [ "$uefiyn" == "y" ]; then
+    mkfs.fat -F 32 "$BOOT_PART"  || { echo "Failed to format boot partition"; exit 1; } 
+fi
 
 if [ "$swapyn" == "y" ]; then
     mkswap "$SWAP_PART" || { echo "Failed to format swap partition"; exit 1; } 
 fi
 
-echo "Formating partitions..."
-mkfs.fat -F 32 "$BOOT_PART"  || { echo "Failed to format boot partition"; exit 1; } 
+
+
 mkfs.ext4 -F "$ROOT_PART"  || { echo "Failed to format root partition"; exit 1; } 
 echo "Success."
 
 bash "$BASH_SCRIPTS_DIR/mountingscript" || { echo "install_base failed"; exit 1; }
-#tes
diff --git a/bash/mountingscript b/bash/mountingscript
--- a/bash/mountingscript
+++ b/bash/mountingscript
@@ -21,14 +21,23 @@ else
     PART_SEP=""
 fi
 
-BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
 
-if [ "$swapyn" == "y" ]; then
-    ROOT_PART="${DISK}${PART_SEP}3" || { echo "Failed to define root partition"; exit 1; } 
-    SWAP_PART="${DISK}${PART_SEP}2" || { echo "Failed to define swap partition"; exit 1; } 
-    echo "Success."
-else 
-    ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
+if [ "$uefiyn" == "y" ]; then
+    BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
+
+    if [[ "$swapyn" == "y" ]]; then
+        SWAP_PART="${DISK}${PART_SEP}2" || { echo "Failed to define swap partition"; exit 1; } 
+        ROOT_PART="${DISK}${PART_SEP}3" || { echo "Failed to define root partition"; exit 1; } 
+    else
+        ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
+    fi
+else
+    if [[ "$swapyn" == "y" ]]; then
+        SWAP_PART="${DISK}${PART_SEP}1" || { echo "Failed to define swap partition"; exit 1; } 
+        ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
+    else
+        ROOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define root partition"; exit 1; } 
+    fi
 fi
 
 # Mount Root
@@ -36,11 +45,13 @@ echo "Mounting root..."
 mount "$ROOT_PART" /mnt
 echo "Success."
 
-# Mount Boot 
-echo "Mounting boot..."
-mkdir -p /mnt/boot
-mount "$BOOT_PART" /mnt/boot
-echo "Success."
+# Mount Boot
+if [ "$uefiyn" == "y" ]; then
+    echo "Mounting boot..."
+    mkdir -p /mnt/boot
+    mount "$BOOT_PART" /mnt/boot
+    echo "Success."
+fi
 
 # Enable Swap
 if [ "$swapyn" == "y" ]; then
@@ -51,3 +62,4 @@ fi
 
 
 echo "Disk $DISK has been partitioned, formatted, and mounted to /mnt."
+
diff --git a/bash/partitionscript b/bash/partitionscript
--- a/bash/partitionscript
+++ b/bash/partitionscript
@@ -14,42 +14,74 @@ if [[ ! -f "$VARS_FILE" ]]; then
 fi
 source "$VARS_FILE"
 
-
-echo "Creating partition table..."
-parted -s "$TARGET_DISK" mklabel gpt || { echo "Faild to create partition table"; exit 1; }
-echo "Success."
-
-echo "Creating UEFI Boot Partition (1GiB)..."
-parted -s "$TARGET_DISK" mkpart primary fat32 1MiB 1025MiB || { echo "Faild to create UEFI boot partition."; exit 1; }
-parted -s "$TARGET_DISK" set 1 esp on || { echo "Faild to create UEFI boot partition."; exit 1; }
-echo "Success."
-
-rootstart=1025
-
-
-if [ "$swapyn" = "y" ]; then
-    echo "Creating Swap Partition ($swapsize)..."
-    swapstart="${rootstart}MiB"
-    swapend="$((rootstart + swapsize))MiB"
-    parted -s "$TARGET_DISK" mkpart primary linux-swap "$swapstart" "$swapend" || { echo "Failed to create swap partition."; exit 1; }
+if [ "$uefiyn" = "y" ]; then
+    echo "Creating partition table..."
+    parted -s "$TARGET_DISK" mklabel gpt || { echo "Faild to create partition table"; exit 1; }
     echo "Success."
 
-    rootstart=$((rootstart + swapsize))
-fi
-
-if [ "$rootyn" = "y" ]; then
-    echo "Creating root partition... (100%)"
-    parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" 100% || { echo "Failed to create root partition."; exit 1; }
+    echo "Creating UEFI Boot Partition (1GiB)..."
+    parted -s "$TARGET_DISK" mkpart primary fat32 1MiB 1025MiB || { echo "Faild to create UEFI boot partition."; exit 1; }
+    parted -s "$TARGET_DISK" set 1 esp on || { echo "Faild to create UEFI boot partition."; exit 1; }
     echo "Success."
+
+    rootstart=1025
+
+
+    if [ "$swapyn" = "y" ]; then
+        echo "Creating Swap Partition ($swapsize)..."
+        swapstart="${rootstart}MiB"
+        swapend="$((rootstart + swapsize))MiB"
+        parted -s "$TARGET_DISK" mkpart primary linux-swap "$swapstart" "$swapend" || { echo "Failed to create swap partition."; exit 1; }
+        echo "Success."
+
+        rootstart=$((rootstart + swapsize))
+    fi
+
+    if [ "$rootyn" = "y" ]; then
+        echo "Creating root partition... (100%)"
+        parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" 100% || { echo "Failed to create root partition."; exit 1; }
+        echo "Success."
+    else 
+        echo "Creating root partition ($rootsize)..."
+        rootend=$((rootstart + rootsize))
+        parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB" || { echo "Failed to create root partition."; exit 1; }
+        echo "Success."
+    fi
+
+    echo "Successfully created UEFI, root and swap partition."
+
+    bash "$BASH_SCRIPTS_DIR/formatscript" || { echo "install_base failed"; exit 1; }
 else 
-    echo "Creating root partition ($rootsize)..."
-    rootend=$((rootstart + rootsize))
-    parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB" || { echo "Failed to create root partition."; exit 1; }
+    echo "Creating partition table..."
+    parted -s "$TARGET_DISK" mklabel msdos || { echo "Faild to create partition table"; exit 1; }
     echo "Success."
+
+    rootstart=1
+
+    if [ "$swapyn" = "y" ]; then
+        echo "Creating Swap Partition ($swapsize)..."
+        swapstart="${rootstart}MiB"
+        swapend="$((rootstart + swapsize))MiB"
+        parted -s "$TARGET_DISK" mkpart primary linux-swap "$swapstart" "$swapend" || { echo "Failed to create swap partition."; exit 1; }
+        echo "Success."
+
+        rootstart=$((rootstart + swapsize))
+    fi
+
+    if [ "$rootyn" = "y" ]; then
+        echo "Creating root partition... (100%)"
+        parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" 100% || { echo "Failed to create root partition."; exit 1; }
+        echo "Success."
+    else 
+        echo "Creating root partition ($rootsize)..."
+        rootend=$((rootstart + rootsize))
+        parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB" || { echo "Failed to create root partition."; exit 1; }
+        echo "Success."
+    fi
+
+    echo "Successfully created UEFI, root and swap partition."
+
+    bash "$BASH_SCRIPTS_DIR/formatscript" || { echo "install_base failed"; exit 1; }
+
 fi
-
-echo "Successfully created UEFI, root and swap partition."
-
-bash "$BASH_SCRIPTS_DIR/formatscript" || { echo "install_base failed"; exit 1; }
-
 
